name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '10.x'

            - name: Install and Build
              run: |
                  npm ci --prefix website
                  npm run build --prefix website

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3-beta
              with:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: master # The branch the action should deploy from.
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: website/build # The folder the action should deploy.
